name: WakaTime status update 

on:
  push:
        branches: [main]
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: '1 0 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses:  DionneNoellaBarretto/dionnenoellabarretto@main
        with:
          WAKATIME_API_KEY: 5ce19e04-14e6-447b-b75f-4e010fc9840c
          GITHUB_TOKEN: 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
          BRANCH: "main"
          COMMIT_MSG: "Automated WAKA Coding Activity Update :alien:"
          SHOW_SHORT_INFO: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
