# name: Waka Readme

# on:
#   schedule:
#     # Runs EVERY 5 MINUTES
#     - cron: "5 * * * *"

# jobs:
#   update-readme:
#     name: Update Readme with Metrics
#     runs-on: ubuntu-latest
# #     https://github.com/athul/waka-readme
#     steps: 
#       - uses:
#         with:
#           REPOSITORY: DionneNoellaBarretto/dionnenoellabarretto
#           WAKATIME_API_KEY: 
#           API_BASE_URL: https://wakapi.dev/api
# #           GH_TOKEN: 


name: WakaTime status update 

on:
  schedule:
    # Runs at 12 am  '0 0 * * *'  UTC
    - cron: '1 0 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses:  DionneNoellaBarretto/dionnenoellabarretto@main
        with:
          WAKATIME_API_KEY: 5ce19e04-14e6-447b-b75f-4e010fc9840c
          GITHUB_TOKEN: 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
          BRANCH: "main"
          COMMIT_MSG: "Automated WAKA Coding Activity Update :alien:"
          SHOW_SHORT_INFO: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
