# This is a basic workflow to help you get started with Actions

name: DailyDev Status

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/59 * * * *"
    
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
