# name: Blog Posts
# on:
#   schedule:
#     # Runs every hour
#     - cron: '0 * * * *'
#   workflow_dispatch:

# jobs:
#   update-readme-with-blog:
#     name: Update blog posts in readme.md
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: gautamkrishnar/blog-post-workflow@master
#         with:
#           max_post_count: "10"
# #          # will need to be updated: https://help.medium.com/hc/en-us/articles/214874118-Using-RSS-feeds-of-profiles-and-publications 
#           feed_list: "https://dev.to/feed/dionnenoellabarretto,https://medium.com/feed/@denverdionne"


name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
     - uses: siddharth2016/quote-readme@main
     - with:
        OPTION: both            # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact
