name: Update Quote Readme

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
     - uses: siddharth2016/quote-readme@main
     - with:
        OPTION: both            # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact
