name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:

    - cron: "*/5 * * * *"

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          OPTION: both            # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact

