name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '5 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: dionnenoellabarretto/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: 0659006a-ade7-417d-a59d-6ce3bb35daf1
          GH_TOKEN: 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
